os: osx
osx_image: xcode11.3
language: objective-c
cache:
  - bundler
  - cocoapods

stages:
  - checks
  - test

before_script:
  - '[ ! -z $DANGER_GITHUB_API_TOKEN ] && bundle exec danger || echo "Skipping Danger for External Contributor"'

jobs:
  include:
    - stage: checks
      # This only needs to be run once, so restrict it to an arbitrary combination
      before_install:
        - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/e3496d9/Formula/clang-format.rb
        - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/7963c3d/Formula/swiftformat.rb
        - pip install flake8
      script:
        - ./scripts/check.sh --test-only

    - stage: test
      osx_image: xcode11 # Xcode 11.0 for zip builder
      script:
        - travis_wait 30 ./scripts/build_zip.sh

branches:
  only:
    - master
    - pb-zip-ci
