os: osx
osx_image: xcode9.2
language: objective-c
cache:
  - bundler
  - cocoapods

rvm: 2.3.1

jobs:
  include:
    - stage: checks
      # This only needs to be run once, so restrict it to an arbitrary combination
      before_install:
        - brew install clang-format
        - brew install swiftformat
      script:
        - ./scripts/check_whitespace.sh
        - ./scripts/check_copyright.sh
        - ./scripts/style.sh test-only $TRAVIS_COMMIT_RANGE
        # Google C++ style compliance
        - ./scripts/lint.sh $TRAVIS_COMMIT_RANGE

    - stage: test
      env:
        - PROJECT=Firebase PLATFORM=iOS
      before_install:
        - |
          if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
            SKIP_FIREBASE=0
            SKIP_FIRESTORE=0
          else
            git diff --name-only $TRAVIS_COMMIT_RANGE | grep -Eq '^(Firebase|Example)'
            SKIP_FIREBASE="$?"
            git diff --name-only $TRAVIS_COMMIT_RANGE | grep -q Firestore
            SKIP_FIRESTORE="$?"
          fi

        # Add next line back with updated DeviceUDID for xcode9.1 if stability issues with simulator
        # - open -a "simulator" --args -CurrentDeviceUDID ABBD7191-486B-462F-80B4-AE08C5820DA1
        - bundle install
        - gem install xcpretty
        - |
          if [[ $SKIP_FIREBASE != 1 ]]; then
            bundle exec pod install --project-directory=Example --repo-update
          fi
      script:
        - |
          if [ $SKIP_FIREBASE != 1 ]; then
            ./scripts/build.sh $PROJECT $PLATFORM
          fi

        # Only need to run pod lib lint in one configuration.
        - |
          # TODO fix os_log deprecation warning in FIRLogger to remove --allow-warnings
          if [ $SKIP_FIREBASE != 1 && $PLATFORM == iOS ]; then
            bundle exec pod lib lint FirebaseCore.podspec --allow-warnings
          fi

        # TODO - Uncomment subsequent lines once FirebaseCore source repo is in public Specs repo
        #  - bundle exec pod lib lint FirebaseAuth.podspec
        #  - bundle exec pod lib lint FirebaseDatabase.podspec
        #  - bundle exec pod lib lint FirebaseMessaging.podspec --allow-warnings #pending #390 fix
        #  - bundle exec pod lib lint FirebaseStorage.podspec
        #  - bundle exec pod lib lint Firestore/Firestore.podspec

    - stage: test
      env:
        - PROJECT=Firebase PLATFORM=macOS
      before_install:
        - |
          if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
            SKIP_FIREBASE=0
            SKIP_FIRESTORE=0
          else
            git diff --name-only $TRAVIS_COMMIT_RANGE | grep -Eq '^(Firebase|Example)'
            SKIP_FIREBASE="$?"
            git diff --name-only $TRAVIS_COMMIT_RANGE | grep -q Firestore
            SKIP_FIRESTORE="$?"
          fi

        # Add next line back with updated DeviceUDID for xcode9.1 if stability issues with simulator
        # - open -a "simulator" --args -CurrentDeviceUDID ABBD7191-486B-462F-80B4-AE08C5820DA1
        - bundle install
        - gem install xcpretty
        - |
          if [[ $SKIP_FIREBASE != 1 ]]; then
            bundle exec pod install --project-directory=Example --repo-update
          fi
      script:
        - |
          if [ $SKIP_FIREBASE != 1 ]; then
            ./scripts/build.sh $PROJECT $PLATFORM
          fi

    - stage: test
      env:
        - PROJECT=Firebase PLATFORM=tvOS
      before_install:
        - |
          if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
            SKIP_FIREBASE=0
            SKIP_FIRESTORE=0
          else
            git diff --name-only $TRAVIS_COMMIT_RANGE | grep -Eq '^(Firebase|Example)'
            SKIP_FIREBASE="$?"
            git diff --name-only $TRAVIS_COMMIT_RANGE | grep -q Firestore
            SKIP_FIRESTORE="$?"
          fi

        # Add next line back with updated DeviceUDID for xcode9.1 if stability issues with simulator
        # - open -a "simulator" --args -CurrentDeviceUDID ABBD7191-486B-462F-80B4-AE08C5820DA1
        - bundle install
        - gem install xcpretty
        - |
          if [[ $SKIP_FIREBASE != 1 ]]; then
            bundle exec pod install --project-directory=Example --repo-update
          fi
      script:
        - |
          if [ $SKIP_FIREBASE != 1 ]; then
            ./scripts/build.sh $PROJECT $PLATFORM
          fi

    - stage: test
      env:
        - PROJECT=Firestore PLATFORM=iOS METHOD=xcodebuild
      before_install:
        - |
          if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
            SKIP_FIREBASE=0
            SKIP_FIRESTORE=0
          else
            git diff --name-only $TRAVIS_COMMIT_RANGE | grep -Eq '^(Firebase|Example)'
            SKIP_FIREBASE="$?"
            git diff --name-only $TRAVIS_COMMIT_RANGE | grep -q Firestore
            SKIP_FIRESTORE="$?"
          fi

        # Add next line back with updated DeviceUDID for xcode9.1 if stability issues with simulator
        # - open -a "simulator" --args -CurrentDeviceUDID ABBD7191-486B-462F-80B4-AE08C5820DA1
        - bundle install
        - gem install xcpretty
        - |
          if [[ $SKIP_FIRESTORE != 1 ]]; then
            bundle exec pod install --project-directory=Firestore/Example --repo-update
          fi
      script:
        - |
          if [ $SKIP_FIRESTORE != 1 ]; then
            ./scripts/build.sh $PROJECT $PLATFORM $METHOD
          fi

    - stage: test
      env:
        - PROJECT=Firestore PLATFORM=macOS METHOD=cmake
      before_install:
        - |
          if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
            SKIP_FIREBASE=0
            SKIP_FIRESTORE=0
          else
            git diff --name-only $TRAVIS_COMMIT_RANGE | grep -Eq '^(Firebase|Example)'
            SKIP_FIREBASE="$?"
            git diff --name-only $TRAVIS_COMMIT_RANGE | grep -q Firestore
            SKIP_FIRESTORE="$?"
          fi
        - brew install cmake
        - brew install go # Somehow the build for Abseil requires this.
        - |
          if [[ $SKIP_FIRESTORE != 1 ]]; then
            bundle exec pod install --project-directory=Firestore/Example --repo-update
          fi
      script:
        - |
          if [ $SKIP_FIRESTORE != 1 ]; then
            ./scripts/build.sh $PROJECT $PLATFORM $METHOD
          fi

branches:
  only:
    - master
