osx_image: xcode9.2
language: objective-c
cache:
  - bundler
  - cocoapods

rvm: 2.3.1
before_install:
# Add next line back with updated DeviceUDID for xcode9.1 if stability issues with simulator
#  - open -a "simulator" --args -CurrentDeviceUDID ABBD7191-486B-462F-80B4-AE08C5820DA1
  - bundle install
  - gem install xcpretty
  - bundle exec pod install --project-directory=Example --repo-update
  - bundle exec pod install --project-directory=Firestore/Example --no-repo-update
  - brew install clang-format
  - |
    echo "$TRAVIS_COMMIT_RANGE"
    echo "$TRAVIS_PULL_REQUEST"
    if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      SKIP_FIREBASE=0
      SKIP_FIRESTORE=0
    else
      git diff --name-only $TRAVIS_COMMIT_RANGE | grep -Eq '^(Firebase | Example)'
      SKIP_FIREBASE="$?"
      git diff --name-only $TRAVIS_COMMIT_RANGE | grep -q Firestore
      SKIP_FIRESTORE="$?"
    fi

script:
  - "! git grep -I ' $'" # Fail on trailing whitespace in non-binary files
  - ./scripts/style.sh test-only # Validate clang-format compliance
  - [ $SKIP_FIREBASE == 1 ] || ./test.sh
  - [ $SKIP_FIRESTORE == 1 ] || ./Firestore/test.sh

# TODO fix os_log deprecation warning in FIRLogger to remove --allow-warnings
  - [ $SKIP_FIREBASE == 1 ] || bundle exec pod lib lint FirebaseCore.podspec --allow-warnings

# TODO - Uncomment subsequent lines once FirebaseCore source repo is in public Specs repo
#  - bundle exec pod lib lint FirebaseAuth.podspec
#  - bundle exec pod lib lint FirebaseDatabase.podspec
#  - bundle exec pod lib lint FirebaseMessaging.podspec --allow-warnings #pending #390 fix
#  - bundle exec pod lib lint FirebaseStorage.podspec
#  - bundle exec pod lib lint Firestore/Firestore.podspec

branches:
  only:
    - master
