name: app_check

on:
  pull_request:
    paths:
    - 'FirebaseAppCheck**'
    - '.github/workflows/app_check.yml'
  schedule:
    # Run every day at 11pm (PST) - cron uses UTC times
    - cron:  '0 7 * * *'

jobs:
  pod_lib_lint:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Bundler
      run: scripts/setup_bundler.sh
    - name: FirebaseAppCheck
      # TODO: Remove --allow-warnings when stabilized.
      run: scripts/third_party/travis/retry.sh scripts/pod_lib_lint.rb FirebaseAppCheck.podspec --allow-warnings

  app_check-cron-only:
    runs-on: macos-latest
    if: github.event_name == 'schedule'
    strategy:
      matrix:
        flags: [
          '--use-modular-headers',
          '--use-libraries'
        ]
    needs: pod_lib_lint
    steps:
    - uses: actions/checkout@v2
    - name: Setup Bundler
      run: scripts/setup_bundler.sh
    - name: PodLibLint FirebaseAppCheck Cron
      # TODO: Remove --allow-warnings when stabilized.
      run: scripts/third_party/travis/retry.sh scripts/pod_lib_lint.rb FirebaseAppCheck.podspec --platforms=ios ${{ matrix.flags }}
