name: CRON

on:
  schedule:
    # Run every day at 8am
    - cron:  '0 8 * * *'

  zip:
    needs: check
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@pb-zip-ci
    - name: Set up
      run: |
        bundle install
        bundle exec pod --version
    - name: ZipBuildingTest
      run: ./scripts/build_zip.sh
