name: CRON

on:
  schedule:
    # Run every day at 10am (PST) - cron uses UTC times
    - cron:  '0 18 * * *'

jobs:
  zip:
    needs: check
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@pb-zip-ci
    - name: Set up
      run: |
        bundle install
        bundle exec pod --version
    - name: ZipBuildingTest
      run: ./scripts/build_zip.sh
