name: CRON

on:
  schedule:
    # Run every 5 minutes
    - cron:  '*/5 * * * *'

jobs:
  zip:
    needs: check
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@pb-zip-ci
    - name: TestingCron
      run: |
        echo "Testing"
        echo `date`
