name: heartbeat_logging

on:
  pull_request:
    paths:
    - 'HeartbeatLogging**'
    - '.github/workflows/heartbeat_logging.yml'

  # TODO(nickcooke): Schedule cron job.

jobs:

  # TODO(nickcooke): Configure `CocoaPods` job(s).

  spm:
    # Don't run on private repo unless it is a PR.
    if: (github.repository == 'Firebase/firebase-ios-sdk' && github.event_name == 'schedule') || github.event_name == 'pull_request'
    runs-on: macos-11
    strategy:
      matrix:
        target: [iOS, tvOS, macOS, catalyst, watchOS]
    steps:
    - uses: actions/checkout@v2
    - name: Initialize xcodebuild
      run: scripts/setup_spm_tests.sh
    - name: HeartbeatLoggingTests
      run: scripts/third_party/travis/retry.sh ./scripts/build.sh HeartbeatLoggingTests ${{ matrix.target }} spm
