name: generate_notices

on:
  pull_request:
    paths:
    - '.github/workflows/notice_generation.yml'
    - '.github/actions/notices_generation**'
jobs:
  generate_a_notice:
    # Don't run on private repo.
    if: github.repository == 'Firebase/firebase-ios-sdk' && github.event_name != 'schedule'
    runs-on: macos-11
    name: Generate NOTICES
    env: 
      NOTICES_PATH:   "${GITHUB_WORKSPACE}/CoreOnly/NOTICES"
    steps:
    - uses: actions/checkout@v2
    - name: Get all pod names
      run: |
        cd "${GITHUB_WORKSPACE}/ReleaseTooling/"
        swift run manifest --pod-name-output-file-path ./output.txt
        PODS=`cat ./output.txt`
        echo "PODS=${PODS}" >> $GITHUB_ENV
    - name: Create a local specs repo
      run: |
        cd "${GITHUB_WORKSPACE}/ReleaseTooling/"
        swift run podspecs-tester --git-root "${GITHUB_WORKSPACE}"
    - name: Create a NOTICES file
      id: notices
      uses: ./.github/actions/notices_generation/
      with:
        pods: ${{ env.PODS }}
        sources: "https://github.com/firebase/SpecsTesting,https://github.com/firebase/SpecsStaging,https://cdn.cocoapods.org"
        min-ios-version: "13.0"
        search-local-pod-version: true
        notices-path:  "${GITHUB_WORKSPACE}/CoreOnly/NOTICES"
  - name: Create a pull request
    run: |
      cd "${GITHUB_WORKSPACE}/scripts/"
      ruby create_pull_request.rb --repo-root ${GITHUB_WORKSPACE} --repo-token ${{ secrets.GITHUB_TOKEN }} --notices-path  "${NOTICES_PATH}"
    shell: bash
