name: generate_notices

on:
  pull_request:
    paths:
    - '.github/workflows/testing_actions.yml'
    - '.github/actions/notices_generation**'
jobs:
  generate_a_notice:
    # Don't run on private repo.
    if: github.repository == 'Firebase/firebase-ios-sdk' && github.event_name != 'schedule'
    runs-on: ubuntu-latest
    name: Generate NOTICES
    steps:
    - uses: actions/checkout@v2
    - name: Get All Pod Names
      id: pod_names
      run: |
        cd "${GITHUB_WORKSPACE}/RleaseTooling/"
        swift run manifest --pod-name-output-file-path ./output.txt
        PODS = `cat ./output.txt`
        echo "PODS=${PODS}" >> $GITHUB_ENV

    - name: Create a NOTICES file
      id: notices
      uses: ./.github/actions/notices_generation/
      with:
        pods: ${{ env.PODS }}
        sources: "https://cdn.cocoapods.org"
