name: spectesting

on:
  pull_request

jobs:
  specs_testing:
    # Don't run on private repo unless it is a PR.
    if: github.repository == 'Firebase/firebase-ios-sdk'
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Check updated files
      run: echo "check updated files"
    - name: Init podspecs and source
      run: |
        cd ReleaseTooling
        swift run podspecs-tester --git-root "${GITHUB_WORKSPACE}"
        find "${HOME}/.cocoapods/" -type f
    - name: List spec repos
      run: pod repo list
    - name: Test
      # The SpecsTesting repo was updated by podspec-tester to point to the head of a PR.
      run: pod spec lint FirebaseABTesting.podspec --sources=https://github.com/firebase/SpecsTesting,https://cdn.cocoapods.org/

