name: spectesting

on:
  pull_request

jobs:
  specs_testing:
    # Don't run on private repo unless it is a PR.
    if: github.repository == 'Firebase/firebase-ios-sdk'
    runs-on: macos-11
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: check files
      id: check_files
      env:
        pr_branch: ${{ github.event.pull_request.head.ref }}
      run: |
        ./scripts/health_metrics/get_updated_files.sh -p output.txt
        ls 
        cat  output.txt
    - name: Init podspecs and source
      run: |
        cd ReleaseTooling
        swift run podspecs-tester --git-root "${GITHUB_WORKSPACE}"
        find "${HOME}/.cocoapods/" -type f
    - name: List spec repos
      run: pod repo list
    - name: Test
      # The SpecsTesting repo was updated by podspec-tester to point to the head of a PR.
      run: pod spec lint FirebaseABTesting.podspec --sources=https://github.com/firebase/SpecsTesting,https://cdn.cocoapods.org/

