name: spectesting

on:
  pull_request

jobs:
  specs_checking:
    # Don't run on private repo unless it is a PR.
    if: github.repository == 'Firebase/firebase-ios-sdk'
    runs-on: macos-11
    outputs:
      matrix: ${{ steps.check_files.outputs.matrix }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: check files
      id: check_files
      env:
        pr_branch: ${{ github.event.pull_request.head.ref }}
      run: |
        ./scripts/health_metrics/get_updated_files.sh -p output.json
        cat output.json
        echo "::set-output name=matrix::{\"include\":$( cat output.json)}"
  specs_testing:
    needs: specs_checking
    runs-on: macos-11
    strategy:
      matrix: ${{fromJson(needs.specs_checking.outputs.matrix)}}
    env:
      PODSPEC: ${{ matrix.podsepc }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Init podspecs and source
      run: |
        mkdir specTestingLogs
        cd ReleaseTooling
        swift run podspecs-tester --git-root "${GITHUB_WORKSPACE}" --podspec ${PODSPEC} --temp-log-dir "${GITHUB_WORKSPACE}/specTestingLogs" 
    - name: Upload Failed Testing Logs
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: specTestingLogs
        path: specTestingLogs/*.txt
