name: spm-visionos

on:
  pull_request:
    paths:
    - '.github/workflows/spm-visionos.yml'
    - 'Package.swift'
    - '.swiftpm/*'
    - 'scripts/build.sh'
    - 'SwiftPMTests/*'
    - 'SwiftPM-PlatformExclude'
    - 'Gemfile*'
  schedule:
    # Run every day at 12am (PST) - cron uses UTC times
    - cron:  '0 8 * * *'

# This workflow builds and tests the Swift Package Manager. Only iOS runs on PRs
# because each platform takes 15-20 minutes after adding Firestore.

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
  visionos-build:
    # Don't run on private repo unless it is a PR.
    if: (github.repository == 'Firebase/firebase-ios-sdk' && github.event_name == 'schedule') || github.event_name == 'pull_request'

    strategy:
      matrix:
        # Full set of Firebase-Package tests only run on iOS. Run subset on other platforms.
        target: [visionOS]
        os: [macos-13]
        include:
          - os: macos-13
            xcode: Xcode_15.2
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: mikehardy/buildcache-action@c87cea0ccd718971d6cc39e672c4f26815b6c126
      with:
        cache_key: platforms${{ matrix.os }}-${{ matrix.xcode }}-${{ matrix.target }}
    - name: Xcode
      run: sudo xcode-select -s /Applications/${{ matrix.xcode }}.app/Contents/Developer
    - name: Initialize xcodebuild
      run: scripts/setup_spm_tests.sh
    - name: Objc Import Tests
      run: scripts/third_party/travis/retry.sh ./scripts/build.sh objc-import-test ${{ matrix.target }} spmbuildonly
    - name: Swift Tests
      run: scripts/third_party/travis/retry.sh ./scripts/build.sh swift-test ${{ matrix.target }} spmbuildonly
    - name: Version Tests
      run: scripts/third_party/travis/retry.sh ./scripts/build.sh version-test ${{ matrix.target }} spmbuildonly
