name: spm

on:
  pull_request:
    paths:
    - '.github/workflows/spm.yml'
    - 'Package.swift'
    - 'Gemfile'
  schedule:
    # Run every day at 12am (PST) - cron uses UTC times
    - cron:  '0 8 * * *'

# This workflow builds and tests the Swift Package Manager. Only iOS runs on PRs
# because each platform takes 15-20 minutes after adding Firestore.

jobs:
  firebase-iOS-build-run:
    # Don't run on private repo unless it is a PR.
    if: (github.repository == 'Firebase/firebase-ios-sdk' && github.event_name == 'schedule') || github.event_name == 'pull_request'
    runs-on: macOS-latest
    strategy:
      matrix:
        test: [
        ABTestingUnit,
        AppDistributionUnit,
        AuthUnit,
        CoreUnit,
        DatabaseUnit,
        FirebaseMLModelDownloaderUnit,
        MessagingUnit,
        RemoteConfigUnit,
        StorageUnit
        ]
    steps:
    - uses: actions/checkout@v2
    - name: Xcode 12
      run: sudo xcode-select -s /Applications/Xcode_12.app/Contents/Developer
    - name: Initialize xcodebuild
      run: xcodebuild -list
    - name: iOS Unit Tests
      run: ./scripts/build.sh ${{ matrix.test }} iOS spm

  platforms:
    # Don't run on private repo unless it is a PR.
    if: (github.repository == 'Firebase/firebase-ios-sdk' && github.event_name == 'schedule') || github.event_name == 'pull_request'
    runs-on: macOS-latest
    strategy:
      matrix:
        target: [iOs, tvOS, macOS, catalyst]
        # Full set of Firebase-Package tests only run on iOS because of Analytics.
        test: [objc-import-test, swift-test, version-test]
    steps:
    - uses: actions/checkout@v2
    - name: Xcode 12
      run: sudo xcode-select -s /Applications/Xcode_12.app/Contents/Developer
    - name: Initialize xcodebuild
      run: xcodebuild -list
    - name: Unit Tests
      run: ./scripts/build.sh ${{ matrix.test }} ${{ matrix.target }} spm
