name: storage

on:
  pull_request:
    paths:
    - 'FirebaseStorage**'
    - '.github/workflows/storage.yml'
  schedule:
    # Run every day at 11pm (PST) - cron uses UTC times
    - cron:  '0 7 * * *'

jobs:
  storage:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Bundler
      run: scripts/setup_bundler.sh
    - name: Install Secret GoogleService-Info.plist
      env:
         plist_secret: ${{ secrets.StoragePlistSecret }}
      run: ./scripts/decrypt_gha_secret.sh scripts/gha-encrypted/storage-db-plist.gpg \
          FirebaseStorage/Tests/Integration/Resources/GoogleService-Info.plist "$plist_secret"
    - name: BuildAndTest # can be replaced with pod lib lint with CocoaPods 1.10
      run: scripts/third_party/travis/retry.sh scripts/build.sh Storage all

  catalsyt:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Bundler
      run: scripts/setup_bundler.sh
    - name: Setup project and Build for Catalyst
      # TODO - Change the "build" to "test" when CocoaPods 1.10.0 is available
      # and it becomes possible to select only the unit tests.
      run: scripts/test_catalyst.sh FirebaseStorage build

  pod-lib-lint:
    runs-on: macOS-latest

    strategy:
      matrix:
        target: [ios, tvos, macos, watchos]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Bundler
      run: scripts/setup_bundler.sh
    - name: Build and test
      run: scripts/third_party/travis/retry.sh scripts/pod_lib_lint.rb FirebaseStorage.podspec --skip-tests --platforms=${{ matrix.target }}

  storage-cron-only:
    runs-on: macos-latest
    if: github.event_name == 'schedule'
    strategy:
      matrix:
        target: [ios, tvos, macos, watchos]
        flags: [
          '--skip-tests --use-modular-headers',
          '--skip-tests --use-libraries'
        ]
    needs: pod-lib-lint
    steps:
    - uses: actions/checkout@v2
    - name: Setup Bundler
      run: scripts/setup_bundler.sh
    - name: PodLibLint Storage Cron
      run: scripts/third_party/travis/retry.sh scripts/pod_lib_lint.rb FirebaseStorage.podspec --platforms=${{ matrix.target }} ${{ matrix.flags }}
