name: storage

on:
  push
#  pull_request:
#    paths:
#    - 'FirebaseStorage**'

jobs:
  core:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Hello world action
      env:
         myString: ${{ 'Mona the Octocat' }}
         #foo: {{ 'my value' }}
         GITHUB_CONTEXT: ${{ toJson(github) }}
         super_secret: ${{ secrets.TestFileSecret }}
      run: |
        echo "abc"
        echo "$myString"
        echo $HOME
        pwd
        ./scripts/decrypt_gha_secret.sh myfile.paul.gpg foo "$super_secret"
        cat foo
        echo "xyz"
        
        
  # cp ${{ secrets.TestSecret }} foo
  #cat foo

    # - uses: actions/checkout@v1
    # - name: Set up
    #   run: |
    #     bundle install
    #     bundle exec pod --version
    # - name: FirebaseCore
    #   run: ./scripts/pod_lib_lint.rb FirebaseCore.podspec --platforms=ios
