name: storage

on:
  push
#  pull_request:
#    paths:
#    - 'FirebaseStorage**'

jobs:
  storage:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Testing
      env:
         plist_secret: ${{ secrets.StoragePlistSecret }}
      run: |
        echo "abc"
        echo \
           "$myString"
    - name: Set up
      run: |
        bundle install
        bundle exec pod --version
        ./scripts/decrypt_gha_secret.sh scripts/gha-encrypted/storage-db-plist.gpg FirebaseStorage/Tests/Integration/Resources/GoogleService-Info.plist "$plist_secret"
    - name: BuildAndTest # can be replaced with pod lib lint with Xcode 1.10
      run: ./scripts/build.sh Storage all
    - name: PodLibLint
      run: |
        ./scripts/pod_lib_lint.rb FirebaseStorage.podspec --skip-tests --platforms=ios
        ./scripts/pod_lib_lint.rb FirebaseStorage.podspec --skip-tests --platforms=macos
        ./scripts/pod_lib_lint.rb FirebaseStorage.podspec --skip-tests --platforms=tvos
