name: generate_notices

on:
  pull_request:
    paths:
    - '.github/workflows/testing_actions.yml'
    - '.github/actions/notices_generation**'
jobs:
  generate_a_notice:
    # Don't run on private repo.
    if: github.repository == 'Firebase/firebase-ios-sdk' && github.event_name != 'schedule'
    runs-on: ubuntu-latest
    name: Generate NOTICES
    steps:
    - uses: actions/checkout@v2
    - name: Create a NOTICES file
      id: notices
      uses: ./.github/actions/notices_generation/
      with:
        pods: "Firebase,FirebaseFunctions"
        sources: "https://cdn.cocoapods.org"
