name: test_coverage

on: [pull_request]
#run specific jobs when specific files are updated.
#https://github.community/t/how-to-execute-jobs-if-folder-updated-recursive/117344/5

jobs:
  check:
    if: github.repository == 'Firebase/firebase-ios-sdk' || github.event_name == 'pull_request'
    name: Check changed files
    outputs:
      database_run_job: ${{ steps.check_files.outputs.database_run_job }}
      functions_run_job: ${{ steps.check_files.outputs.functions_run_job }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: check files
        id: check_files
        env:
          pr_branch: ${{ github.event.pull_request.head.ref }}
        run: ./scripts/code_coverage_report/get_updated_files.sh

  pod-lib-lint-database:
    # Don't run on private repo unless it is a PR.
    if: github.repository == 'Firebase/firebase-ios-sdk' && needs.check.outputs.database_run_job == 'true' || github.event_name == 'push'
    needs: check
    runs-on: macOS-latest
    strategy:
      matrix:
        target: [ios, tvos, macos]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Bundler
      run: scripts/setup_bundler.sh
    - name: Build and test
      env:
        SDK: database
      run: ./scripts/code_coverage_report/pod_test_code_coverage_report.sh FirebaseDatabase "${{ matrix.target }}"
    - uses: actions/upload-artifact@v2
      with:
        name: codecoverage
        path: /Users/runner/*.xcresult

  pod-lib-lint-functions:
    # Don't run on private repo unless it is a PR.
    if: github.repository == 'Firebase/firebase-ios-sdk' && needs.check.outputs.functions_run_job == 'true' || github.event_name == 'push'
    needs: check
    runs-on: macOS-latest

    strategy:
      matrix:
        target: [ios, tvos, macos]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Bundler
      run: scripts/setup_bundler.sh
    - name: Build and test
      run: ./scripts/code_coverage_report/pod_test_code_coverage_report.sh FirebaseFunctions "${{ matrix.target }}"
    - uses: actions/upload-artifact@v2
      with:
        name: codecoverage
        path: /Users/runner/*.xcresult

  create_report:
    needs: [pod-lib-lint-functions, pod-lib-lint-database]
    env:
      metrics_service_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
    if: always()
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Access to Metrics Service
        run: |
          # Install gcloud sdk
          curl https://sdk.cloud.google.com > install.sh
          bash install.sh --disable-prompts
          echo "${HOME}/google-cloud-sdk/bin/" >> $GITHUB_PATH
          export PATH="${HOME}/google-cloud-sdk/bin/:${PATH}"

          scripts/decrypt_gha_secret.sh scripts/gha-encrypted/metrics_service_access.json.gpg \
          metrics-access.json "$metrics_service_secret"
          gcloud auth activate-service-account --key-file metrics-access.json
      - uses: actions/download-artifact@v2
        id: download
        with:
          path: /Users/runner/test
      - name: Compare Diff and Post a Report
        if: github.event_name == 'pull_request'
        env:
          base_commit: ${{ needs.check.outputs.base_commit }}
        run: |
          if [ -d "${{steps.download.outputs.download-path}}" ]; then
          cd scripts/code_coverage_report/generate_code_coverage_report
          swift run CoverageReportGenerator --presubmit "granluo/issue_generations" --commit "testprcommit1" --token $(gcloud auth print-identity-token) --xcresult-dir "/Users/runner/test/codecoverage" --log-link "https://github.com/firebase/firebase-ios-sdk/actions?query=workflow%3Atest_coverage" --pull-request-num 79 --pull-request-note "123" --base-commit "test1commit" --branch "create_issues"
          # swift run CoverageReportGenerator --presubmit "granluo/issue_generations" --commit "testprcommit1" --token $(gcloud auth print-identity-token) --xcresult-dir "/Users/runner/test/" --log-link "https://github.com/firebase/firebase-ios-sdk/actions?query=workflow%3Atest_coverage" --pull-request-num 79 --pull-request-note "123" --base-commit "$base_commit" --branch "create_issues"
          fi
      - name: Update New Coverage Data
        if: github.event_name == 'push'
        run: |
          if [ -d "${{steps.download.outputs.download-path}}" ]; then
          cd scripts/code_coverage_report/generate_code_coverage_report
          swift run CoverageReportGenerator --merge "granluo/issue_generations" --commit "testprcommit1" --token $(gcloud auth print-identity-token) --xcresult-dir "/Users/runner/test/" --log-link "https://github.com/firebase/firebase-ios-sdk/actions?query=workflow%3Atest_coverage" --pull-request-num 79 --pull-request-note "123" --base-commit "test1commit" --branch "create_issues"
          fi
