name: generate_notices

on:
  pull_request:
    paths:
    - '.github/workflows/testing_actions.yml'
    - '.github/actions/notices_generation**'
  schedule:
    # Run every day at 5am (PST) - cron uses UTC times
    - cron:  '0 13 * * *'
jobs:
  generate_a_notice:
    # Don't run on private repo.
    if: github.repository == 'Firebase/firebase-ios-sdk' && github.event_name == 'schedule'
    runs-on: ubuntu-latest
    name: Generate a nightly notices issue
    steps:
    - uses: actions/checkout@v2
    - name: Create a nightly report
      uses: ./.github/actions/notices_generation/
      with:
        access-token: '${{ secrets.GITHUB_TOKEN }}'
        # This is to exclude workflows that will be searched in the nightly report.
        exclude-workflow-files: 'performance-integration-tests.yml'

  test_generate_a_notice:
    # Don't run on private repo.
    if: github.repository == 'Firebase/firebase-ios-sdk' && github.event_name != 'schedule'
    runs-on: ubuntu-latest
    name: Test nightly notices generations
    steps:
    - uses: actions/checkout@v2
    - name: Create a nightly report
      uses: ./.github/actions/notices_generation/
