name: update-cpp-sdk-on-release
on:
  release:
    types: [ published ]
  # Temporary trigger just for testing.
  pull_request:
    types: [ edited ]

jobs:
  trigger-cpp-sdk-update:
    # Only when a new release (not just the CocoaPods-* tag) is published.
    # if: ${{ (github.event_name == 'release' && !contains(github.ref, 'CocoaPods')) }}
    # Fetch an authentication token for firebase-workflow-trigger, then use that
    # token to trigger the update-dependencies workflow in firebase-cpp-sdk.
    name: Trigger C++ SDK update
    runs-on: ubuntu-latest
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Check out firebase-cpp-sdk
        uses: actions/checkout@v2.3.1
        with:
          repository: firebase/firebase-cpp-sdk
          ref: main

      - name: Get firebase-workflow-trigger token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.CPP_WORKFLOW_TRIGGER_APP_ID }}
          private_key: ${{ secrets.CPP_WORKFLOW_TRIGGER_APP_PRIVATE_KEY }}
          repository: firebase/firebase-cpp-sdk

      - name: Trigger firebase-cpp-sdk update
        run: |
          python scripts/gha/trigger_workflow.py -t ${{ steps.generate-token.outputs.token }} -w update-dependencies.yml -p updateAndroid 0 -p updateiOS 1 -s 10 -A
