name: release

on:
  pull_request:
    paths:
    - '.github/workflows/update_specstaging.yml
  schedule:
    # Run every day at 11pm (PST) - cron uses UTC times
    - cron:  '0 7 * * *'

jobs:

  quickstart_release_test:
    # Don't run on private repo unless it is a PR.
    # if: github.repository != 'FirebasePrivate/firebase-ios-sdk' || github.event_name == 'pull_request'
    env:
      plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
      signin_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: SpecStaging Repo clone
      run: |
        find  "${HOME}/.cocoapods/repos" -type d -maxdepth 1 -exec sh -c 'pod repo remove $(basename {})' \;
        pod repo add specstaging https://github.com/firebase/SpecsStaging.git
        find . -name "FirebaseRemoteConfig.podspec" -print -exec pod repo push local {} --sources=https://github.com/firebase/SpecsStaging.git,https://cdn.cocoapods.org/ --skip-tests --local-only \;
