name: 'Testing Report'
description: 'Generate a testing report'
inputs:
  pods:
    description: 'Targeted Pods for licences'
    required: true
  sources:
    description: 'Sources of PodSpecs'
    required: true
    default: 'https://cdn.cocoapods.org'
  min-ios-version:
    description: 'The minimum version of iOS'
    required: true
    default: '10.0'
outputs:
  notices_contents:
    description: 'contents of notices'
runs:
  using: 'composite'
  steps:
  - uses: actions/setup-ruby@v1
    with:
      ruby-version: "2.7"
  - name: First step
    run: |
      cd "${{ github.action_path }}"
      bundle install
      ruby app.rb --pods ${{ inputs.pods }} --sources ${{ inputs.sources }} --min_ios_version ${{ inputs.min-ios-version }}
    shell: bash
  - name: Upload artifacts
    uses: actions/upload-artifact@v3
    with: 
      name: notices
      path: .github/actions/notices_generation/NOTICES
