name: 'Testing Report'
description: 'Generate a testing report'
inputs:
  pods:
    description: 'Targeted Pods for licences'
    required: true
  sources:
    description: 'Sources of PodSpecs'
    required: true
    default: 'https://cdn.cocoapods.org'
  min-ios-version:
    description: 'The minimum version of iOS'
    required: true
    default: '10.0'
outputs:
  notices_contents:
    description: 'contents of notices'
runs:
  #using: 'docker'
  #image: 'Dockerfile'
  using: 'composite'
  steps:
  - uses: actions/setup-ruby@v1
    with:
      ruby-version: "2.7"
  - name: First step
    run: |
      cd .github/actions/notices_generation/
      pwd
      ls
      bundle install
      ruby app.rb
    shell: bash
  - name: Upload artifacts
    uses: actions/upload-artifact@v3
    with: 
      name: notices
      path: |
        ./

